import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: {
      'core/index': 'src/core/index.ts',
      'context/index': 'src/context/index.ts',
      'tools/index': 'src/tools/index.ts',
      'guardrails/index': 'src/guardrails/index.ts',
      'prompt/index': 'src/prompt/index.ts',
      'observe/index': 'src/observe/index.ts',
      'session/index': 'src/session/index.ts',
      'memory/index': 'src/memory/index.ts',
      'eval/index': 'src/eval/index.ts',
      'evolve/index': 'src/evolve/index.ts',
    },
    format: ['esm'],
    dts: true,
    outDir: 'dist',
    clean: true,
    splitting: false,
    treeshake: true,
    target: 'node18',
    sourcemap: true,
  },
  {
    entry: {
      'core/index': 'src/core/index.ts',
      'context/index': 'src/context/index.ts',
      'tools/index': 'src/tools/index.ts',
      'guardrails/index': 'src/guardrails/index.ts',
      'prompt/index': 'src/prompt/index.ts',
      'observe/index': 'src/observe/index.ts',
      'session/index': 'src/session/index.ts',
      'memory/index': 'src/memory/index.ts',
      'eval/index': 'src/eval/index.ts',
      'evolve/index': 'src/evolve/index.ts',
    },
    format: ['cjs'],
    outDir: 'dist/cjs',
    outExtension: () => ({ js: '.cjs' }),
    splitting: false,
    target: 'node18',
    sourcemap: true,
  },
]);
