/**
 * Types for the memory module — memory entries, filters, compaction, and relay state.
 *
 * @module
 */

/** Grade indicating importance of a memory entry. */
export type MemoryGrade = 'critical' | 'useful' | 'ephemeral';

/**
 * A single memory entry stored in a MemoryStore.
 *
 * @example
 * ```ts
 * const entry: MemoryEntry = {
 *   id: 'abc123',
 *   key: 'user-preference',
 *   content: 'Prefers dark mode',
 *   grade: 'useful',
 *   createdAt: Date.now(),
 *   updatedAt: Date.now(),
 * };
 * ```
 */
export interface MemoryEntry {
  /**
   * **Storage handle** — opaque identifier the store assigns when an
   * entry is written. Generated by the store (`MemoryStore.write`)
   * unless the caller pre-allocated one. Treat as a primary key for
   * `MemoryStore.read(id)` / `delete(id)`.
   */
  readonly id: string;
  /**
   * **Caller-meaningful identifier** — supplied by the caller to
   * support `query({ key })` lookups and dedupe/upsert semantics.
   * Distinct from `id`: a store may rotate `id` on overwrite while
   * `key` stays stable. Required because most KV-style use-cases
   * key by domain identifier (`user:42:preferences`), not the
   * synthetic storage handle.
   *
   * Closes showcase 03 FRICTION_LOG `MemoryEntry.write requires an
   * explicit key distinct from id`.
   */
  readonly key: string;
  readonly content: string;
  readonly grade: MemoryGrade;
  readonly createdAt: number;
  readonly updatedAt: number;
  readonly metadata?: Record<string, unknown>;
  readonly tags?: string[];
}

/** Filter criteria for querying memory entries. */
export interface MemoryFilter {
  readonly grade?: MemoryGrade;
  readonly tags?: string[];
  readonly since?: number;
  readonly limit?: number;
  readonly search?: string;
  /** Offset for pagination — skip this many results before applying limit. */
  readonly offset?: number;
  /** When provided, only return entries tagged with this sessionId (via metadata.sessionId). */
  readonly sessionId?: string;
}

/** Options for vector similarity search on embedding-backed stores. */
export interface VectorSearchOptions {
  /** The query embedding vector. */
  readonly embedding: readonly number[];
  /** Maximum number of results to return. */
  readonly limit?: number;
  /** Minimum similarity score threshold (0–1). */
  readonly minScore?: number;
}

/** Policy for compacting (pruning) memory entries. */
export interface CompactionPolicy {
  readonly maxEntries?: number;
  readonly maxAge?: number;
  readonly gradeWeights?: {
    critical: number;
    useful: number;
    ephemeral: number;
  };
}

/** Result of a compaction operation. */
export interface CompactionResult {
  readonly removed: number;
  readonly remaining: number;
  readonly freedEntries: string[];
}

/** State for cross-context relay handoff. */
export interface RelayState {
  readonly progress: Record<string, unknown>;
  readonly artifacts: string[];
  readonly checkpoint: string;
  readonly timestamp: number;
}
