import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: {
      index: 'src/index.ts',
      'core/index': 'src/core/index.ts',
      'context/index': 'src/context/index.ts',
      'tools/index': 'src/tools/index.ts',
      'guardrails/index': 'src/guardrails/index.ts',
      'prompt/index': 'src/prompt/index.ts',
      'observe/index': 'src/observe/index.ts',
      'session/index': 'src/session/index.ts',
      'memory/index': 'src/memory/index.ts',
      'rag/index': 'src/rag/index.ts',
      'orchestration/index': 'src/orchestration/index.ts',
      'evolve-check/index': 'src/evolve-check/index.ts',
      'redact/index': 'src/redact/index.ts',
    },
    format: ['esm'],
    dts: true,
    outDir: 'dist',
    clean: true,
    splitting: false,
    treeshake: true,
    minify: true,
    target: 'node18',
    sourcemap: true,
  },
  {
    entry: {
      index: 'src/index.ts',
      'core/index': 'src/core/index.ts',
      'context/index': 'src/context/index.ts',
      'tools/index': 'src/tools/index.ts',
      'guardrails/index': 'src/guardrails/index.ts',
      'prompt/index': 'src/prompt/index.ts',
      'observe/index': 'src/observe/index.ts',
      'session/index': 'src/session/index.ts',
      'memory/index': 'src/memory/index.ts',
      'rag/index': 'src/rag/index.ts',
      'orchestration/index': 'src/orchestration/index.ts',
      'evolve-check/index': 'src/evolve-check/index.ts',
      'redact/index': 'src/redact/index.ts',
    },
    format: ['cjs'],
    outDir: 'dist/cjs',
    outExtension: () => ({ js: '.cjs' }),
    splitting: false,
    treeshake: true,
    minify: true,
    target: 'node18',
    sourcemap: true,
  },
]);
