#!/usr/bin/env bash
# Re-sign a changesets/action "Version Packages" PR so it satisfies the
# `required_signatures` ruleset on `main`.
#
# WHY THIS EXISTS:
#   `changesets/action` uses GITHUB_TOKEN to push the version-bump
#   commit. Two consequences:
#
#     1. GitHub Actions deliberately does NOT trigger downstream
#        workflows on commits pushed by GITHUB_TOKEN — so the bot's
#        PR sits with no CI runs and stays BLOCKED on
#        `required_status_checks`.
#
#     2. The bot's commit cannot be signed (it's not a GitHub App and
#        has no GPG key) — so it's blocked by `required_signatures`
#        on `main`.
#
#   Until one of the permanent fixes in `docs/release.md` is in place
#   (GitHub App with createCommitOnBranch, or a PAT, or a
#   bypass_actors entry on the ruleset), this script unblocks the
#   release lane in one command.
#
# USAGE:
#   tools/sign-changeset-release-pr.sh <bot-pr-number>
#
# WHAT IT DOES:
#   1. Fetches the bot PR's branch (changeset-release/main).
#   2. Cherry-picks the bot commit onto a fresh branch with -S
#      (maintainer GPG signature).
#   3. Pushes under a `changeset-release/<suffix>` name so the
#      `changeset-check` workflow's skip pattern matches.
#   4. Opens a new PR superseding the bot's, enables auto-merge.
#   5. Closes the bot's original PR.
#
# REQUIREMENTS:
#   - `gh` CLI authenticated
#   - Local git configured for signed commits:
#     `git config user.signingkey` and `git config commit.gpgsign true`
#
# Exit codes: 0 success, 1 misuse, 2 git failure, 3 gh failure.

set -euo pipefail

if [[ "${1:-}" == "" ]]; then
  echo "usage: $(basename "$0") <bot-pr-number>" >&2
  exit 1
fi

BOT_PR="$1"
SUFFIX="signed-$(date -u +%Y%m%dT%H%M%S)"
NEW_BRANCH="changeset-release/${SUFFIX}"

# Sanity: confirm bot PR exists, is open, and lives on the expected branch.
BOT_BRANCH="$(gh pr view "${BOT_PR}" --json headRefName -q .headRefName 2>/dev/null || true)"
if [[ -z "${BOT_BRANCH}" ]]; then
  echo "error: PR #${BOT_PR} not found" >&2
  exit 3
fi
if [[ "${BOT_BRANCH}" != changeset-release/* ]]; then
  echo "error: PR #${BOT_PR} branch is '${BOT_BRANCH}', expected changeset-release/*" >&2
  exit 1
fi

BOT_TITLE="$(gh pr view "${BOT_PR}" --json title -q .title)"

echo "[sign-pr] PR #${BOT_PR} on '${BOT_BRANCH}' — '${BOT_TITLE}'"

# Confirm signing is configured locally.
if ! git config --get user.signingkey > /dev/null 2>&1; then
  echo "error: git user.signingkey not configured locally" >&2
  echo "       run: git config --global user.signingkey <your-key-id>" >&2
  exit 1
fi

# Make sure we're on a clean main mirror.
echo "[sign-pr] syncing local main…"
git checkout main
git pull --ff-only origin main

echo "[sign-pr] fetching bot branch…"
git fetch origin "${BOT_BRANCH}"

echo "[sign-pr] creating signed branch '${NEW_BRANCH}'…"
git checkout -b "${NEW_BRANCH}" main
git cherry-pick -S FETCH_HEAD

# Verify signature actually landed.
SIG_STATUS="$(git log -1 --pretty=format:%G?)"
if [[ "${SIG_STATUS}" != "G" ]]; then
  echo "error: cherry-pick produced unsigned commit (status: ${SIG_STATUS})" >&2
  exit 2
fi
echo "[sign-pr] signature OK (status: ${SIG_STATUS})"

echo "[sign-pr] pushing branch…"
git push -u origin "${NEW_BRANCH}"

echo "[sign-pr] opening superseding PR…"
NEW_PR_URL="$(gh pr create \
  --title "${BOT_TITLE} (signed)" \
  --body "Signed cherry-pick of #${BOT_PR}. Closes / supersedes #${BOT_PR}.

The bot PR was blocked by the \`required_signatures\` ruleset on \`main\`. This re-creates the same diff signed with the maintainer's GPG key.

Generated by \`tools/sign-changeset-release-pr.sh\`.")"
echo "[sign-pr] opened ${NEW_PR_URL}"

NEW_PR="$(echo "${NEW_PR_URL}" | grep -oE '[0-9]+$')"

echo "[sign-pr] enabling auto-merge on PR #${NEW_PR}…"
gh pr merge "${NEW_PR}" --auto --squash || true

echo "[sign-pr] closing superseded bot PR #${BOT_PR}…"
gh pr close "${BOT_PR}" --comment "Superseded by #${NEW_PR} — re-opened with maintainer GPG signature so the commit satisfies the \`required_signatures\` ruleset."

echo ""
echo "[sign-pr] DONE. PR #${NEW_PR} is queued for auto-merge."
echo "[sign-pr] Cleanup tip after merge:"
echo "[sign-pr]   git checkout main && git pull && git fetch --prune origin && git branch -D ${NEW_BRANCH}"
